name: SurvivalTeams
main: net.projectzombie.survivalteams.main.Main
depend: [ConsistentChatAPI]
version: 1.0
commands:
  party:
    description: Nope.
    usage: "WIP"
  tb:
    description: Full suite of Survival Block changes.
    usage: "/tb <add:br:bn:delay:tool:hitpoints:durability:hittool:reload:rsb:rtb:rht:rall>"
